version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - space-network
    container_name: eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  cargo-service:
    build:
      context: ./cargo-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - space-network
    container_name: cargo-service
    depends_on:
      - eureka-server
      - kafka
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  launch-service:
    build:
      context: ./launch-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - space-network
    container_name: launch-service
    depends_on:
      - eureka-server
      - cargo-service
      - kafka
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  destination-service:
    build:
      context: ./destination-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - space-network
    container_name: destination-service
    depends_on:
      - eureka-server
      - kafka
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  telemetry-service:
    build:
      context: ./telemetry-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - space-network
    container_name: telemetry-service
    depends_on:
      - eureka-server
      - kafka
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - space-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - space-network

networks:
  space-network:
    driver: bridge 